### ISSUE TITLE
Project offline?

### ISSUE THREAD

**Issue by lionell88** [Jorl17/open-elevation#27] opened 2018-12-13 10:26 UTC
Hello. I want to download your project to run it locally but something seems to be offline. Docker image also is offline.

**Comment by cpro90** [comment] 2018-12-16 22:01
I guess so :( unfortunately I cannot find any other solution getting free elevation data.

**Comment by bluthen** [comment] 2018-12-17 19:19
I was able to get the docker image today. I needed to download from mirror @sTorro set up to create the dataset. I was also able to run it without docker on my own system. The GDAL requirement was a little tricky but the stackexchange link helped.
https://github.com/Jorl17/open-elevation/issues/22#issuecomment-430130705
https://gis.stackexchange.com/questions/28966/python-gdal-package-missing-header-file-when-installing-via-pip

**Comment by cpro90** [comment] 2018-12-17 20:41
@sTorro do you have the link to your gdrive? :) that would be very nice.

The japanese dataset does not seem like it is in the needed format :/

**Comment by sTorro** [comment] 2018-12-17 20:50
Here you go (#22): https://drive.google.com/drive/folders/1EdpJe9O2vXsKdop_yRr_ZbnPKHakO57j?usp=sharing

Well, the Japanese dataset works well with openelevation server, just needs a "bit" more space ;)

**Comment by cpro90** [comment] 2018-12-17 20:56
Thanks a lot :)

**Comment by bluthen** [comment] 2018-12-17 21:03
Sorry if I wasn't verbose enough, but you just need to modify the create-dataset.sh to not run download-srtm-data.sh and make sure to untar them yourselves. Then run create-dataset.sh

The Japanese ALOS dataset seems cool.

**Comment by sTorro** [comment] 2018-12-18 08:56
Keep in mind the Japanese dataset uncompressed are about 1 TB if I remember well, but the quality is better by far.

**Comment by sTorro** [comment] 2018-12-19 09:31
Maybe is a memory issue. Try to split the TIF files into smaller tiles using /code/create-tiles.sh script.

`docker run -t -i -v $(pwd)/data:/code/data openelevation/open-elevation /code/create-tiles.sh  /code/data/SRTM_NE_250m.tif 10 10`

**Comment by carlos-mg89** [comment] 2019-01-09 11:43
Since my issue is very related (IMHO) with this, I'll continue posting here.

I have tried running the docker machine, by doing the following:
- First, downloaded the gdrive files and unzipped them
- Later, I split the 3 tif files, using the following (and it worked):
```
./create-tiles.sh code/data/SRTM_NE_250m.tif 10 10
./create-tiles.sh code/data/SRTM_SE_250m.tif 10 10
./create-tiles.sh code/data/SRTM_W_250m.tif 10 20
```
- And finally, I run `docker run -t -i -v $(pwd)/data:/code/data -p 8080:8080 openelevation/open-elevation`

To check everything's working, I checked a real location by visiting this URL: http://localhost:8080/api/v1/lookup?locations=48.6089816,-1.5139133

And the result was:
`{"results": [{"latitude": 48.6089816, "longitude": -1.5139133, "error": "No such coordinate (48.6089816, -1.5139133)"}]}`

It seems that somehow the elevation data is not being read. Could anyone help me here please?

**Comment by bluthen** [comment] 2019-01-10 16:14
@carlos-mg89 I'm not sure, maybe make sure all the files are in the right place? That `data` is pointed to the right place. I modified data so it works in docker or my real system.

You can run:
docker run -t -i -v $(pwd)/data:/code/data -p 8080:8080 openelevation/open-elevation bash
To get a bash prompt to see what the docker image sees.

When I run your url I get:
{"results": [{"latitude": 48.6089816, "elevation": 7, "longitude": -1.5139133}]}

**Comment by andrewcooke** [comment] 2019-01-13 18:32
sorry to ask somewhat random qs here but i am not sure where else to ask.  given that the 250m data is unavailable, will the 30m data work?  that does seem to be available (and i could just donwload the areas i am interested in)?  sorry if this is a dumb question - i am new to this.

**Comment by carlos-mg89** [comment] 2019-01-14 10:39
@bluthen I have the elevation data with all the tif files on /code/data (on my Linux computer, the host) and I run the above docker run I posted on open-elevation/docker folder. There, I can see a data folder, but it only contains a summary.json after I run either the docker run I posted or the one you posted.

I think I'm messing things up with the directories. I have tried now movind the data directory, to the open-elevation directory, but the docker/data contains the same summary.json and if I run the docker run, the API call returns the same answer :weary:

**Comment by carlos-mg89** [comment] 2019-01-14 13:15
@bluthen I definitely messed it up with the folders. Now I have created a data folder within the clonned open-elevation project. From there (previously, I executed the docker command, from the open-elevation/docker folder), I run `docker run -t -i -v $(pwd)/data:/code/data -p 8080:8080 openelevation/open-elevation` and voilà! It works like a charm!!!

Thank you so much!

**Comment by Jorl17** [comment] 2019-02-10 17:47
See https://github.com/Jorl17/open-elevation/issues/29#issuecomment-462154786 :)

**Comment by ajnisbet** [comment] 2020-05-22 23:46
I've been working on an API to address some of the outstanding issues with open-elevation, such as: interpolation, `.hgt` support, and offering 30m datasets and bathymetry in a public API.

Code: [ajnisbet/opentopodata](https://github.com/ajnisbet/opentopodata)
Docs & public API: [www.opentopodata.org](https://www.opentopodata.org/)

Hope this is helpful!

**Comment by Jorl17** [comment] 2021-07-30 17:11
Hi.

For the better part of the last 2 years, the API has been completely overloaded (sadly, **very little comes in the way of donations,** and so I can't really pay for a more beefed up machine).

**As of two days ago, though, I have done some tweaks to the backend and the API should be handling the workload much better. Give it a try again!**

I will also be **pushing a series of updates to the repository and dockerhub, to modernize the project and make it work again.**

I will close this issue because I believe that the public API is now working, but feel free to reopen it if it is not. If you have other issues, please open a separate issue for that.

**Closed by Jorl17** 2021-07-30 17:11 UTC

**Comment by iisri-vu** [comment] 2021-09-03 14:34
The problem is inside download-srtm-data sh.
It extract the downloaded file into the 
data/SRTM_NE_250m_TIF/,    data/SRTM_SE_250m_TIF/  and data/SRTM_W_250m_TIF  folder in windows machine.

Also docker server take upto 20GB of ram for SE map.  It runs extremely slow.

**Comment by Jorl17** [comment] 2021-09-03 14:51
Hi @iisri-vu Please open a separate issue for the problem you're having. I'm not sure I understood the issue you are having.

This original issue had to do with the fact the public API at https://open-elevation.com/ was overloaded. That problem has since been fixed.

Regarding the 20GB, it should not be slow, because the files are split into chunks. Perhaps you're having another issue.

I will be waiting for another issue from you.
