### ISSUE TITLE
latitude, logitude reversed

### ISSUE THREAD

**Issue by MichiBB** [Jorl17/open-elevation#78] opened 2023-06-14 10:06 UTC
Hello,
API parameters are latitude,longitude.
In the response the latitude,longitude are reversed. Please try your own sample:
https://api.open-elevation.com/api/v1/lookup?locations=41.161758,-8.583933
Response:
{"results":[{"latitude":-8.583933,"longitude":41.161758,"elevation":117.0}]}

Do I have a mistake in thinking?

Best regards
MichBB

**Comment by Jorl17** [comment] 2023-06-14 11:37
Thank you for pointing this out!

As part of our continued efforts in increasing the performance of the public API, we recently released an internal update of the open-elevation code. We accidentally swapped the latitude and longitude parameters in the response. Note, however, that the elevation value is correct -- it's merely a matter of the output of those two values.

The issue is now fixed. Sorry for the troubles.

**Closed as completed by Jorl17** 2023-06-14 11:37 UTC
